### ISSUE TITLE
Example with openssl

### ISSUE THREAD

**Issue by salrashid123** [Foxboron/go-tpm-keyfiles#1] opened 2024-05-23 15:15 UTC
thanks for authoring this (its just what i was looking for as managing keys is pretty tedious).

if it helps with an example here or as a reference, i confirm some basic cross compatiblity with openssl tss engine 

basiically this create keys, saves to disk using this library, then use openssl to sign/verify and arrive at the same signature value

https://gist.github.com/salrashid123/b2c6083fba2e6339f4b39eee8c4d79c2

**Comment by Foxboron** [comment] 2024-05-23 15:25
Yo,

Thanks for checking out the library :) I actually browsed a bunch of your TPM code when I was originally learning `go-tpm` and TPM stuff last year.

I intend to refactor out all of the TPM specific code from [`ssh-tpm-agent`](https://github.com/Foxboron/ssh-tpm-agent) into this library to help with loading the keys with SRKs and pin/password stuff in the long run.

I also see James has finally merged my `description` field in the ASN.1 spec.

**Comment by salrashid123** [comment] 2024-05-26 16:33
hi-

i looked around a bit more on my long weekend and i think the following helps if the key is using [permanent handle parent](https://www.hansenpartnership.com/draft-bottomley-tpm2-keys.html#section-3.1.8) `(MSO 0x40)`



the specific template for that shown below 


for a full end-to-end where the key is created using `tpm2tss-genkey`
see [TPM Keyfile with permanent handle](https://gist.github.com/salrashid123/6d355e4f03b124c085f780a9b3555dc8)


```golang
	ECCSRKHTemplate = tpm2.TPMTPublic{
		Type:    tpm2.TPMAlgECC,
		NameAlg: tpm2.TPMAlgSHA256,
		ObjectAttributes: tpm2.TPMAObject{
			FixedTPM:            true,
			FixedParent:         true,
			SensitiveDataOrigin: true,
			UserWithAuth:        true,
			NoDA:                true,
			Restricted:          true,
			Decrypt:             true,
		},
		Parameters: tpm2.NewTPMUPublicParms(
			tpm2.TPMAlgECC,
			&tpm2.TPMSECCParms{
				Symmetric: tpm2.TPMTSymDefObject{
					Algorithm: tpm2.TPMAlgAES,
					KeyBits: tpm2.NewTPMUSymKeyBits(
						tpm2.TPMAlgAES,
						tpm2.TPMKeyBits(128),
					),
					Mode: tpm2.NewTPMUSymMode(
						tpm2.TPMAlgAES,
						tpm2.TPMAlgCFB,
					),
				},
				CurveID: tpm2.TPMECCNistP256,
			},
		),
		Unique: tpm2.NewTPMUPublicID(
			tpm2.TPMAlgECC,
			&tpm2.TPMSECCPoint{
				X: tpm2.TPM2BECCParameter{
					Buffer: make([]byte, 0),
				},
				Y: tpm2.TPM2BECCParameter{
					Buffer: make([]byte, 0),
				},
			},
		),
	}
```


---

unrelated to this, i use [go-tpm-tools.client.Key](https://pkg.go.dev/github.com/google/go-tpm-tools/client#Key) in several repos (eg [golang-jwt-tpm](https://github.com/salrashid123/golang-jwt-tpm)) but that accepts a loaded handle.    I'll add a snippet there and elsewhere which uses the keyfiles from here and then initializes go-tpm-tools.client.Key:

```golang
        key, err := keyfile.Decode(c)
	regenRSAKey, err := tpm2.Load{
		ParentHandle: tpm2.AuthHandle{
			Handle: regenPrimary.ObjectHandle,
			Name:   tpm2.TPM2BName(regenPrimary.Name),
			Auth:   tpm2.PasswordAuth([]byte("")),
		},
		InPublic:  key.Pubkey,
		InPrivate: key.Privkey,
	}.Execute(rwr)
	pHandle := tpmutil.Handle(regenRSAKey.ObjectHandle.HandleValue())
	k, err := client.LoadCachedKey(rwc, pHandle, nil)
        r, err := k.GetSigner()
        s, err := r.Sign(rand.Reader, digest[:], crypto.SHA256)
```

i'll also adapt and add samples for other places to save/load keys w/o using permanent handles.. eg [aws-tpm-process-credential](https://github.com/salrashid123/aws-tpm-process-credential))

**Comment by Foxboron** [comment] 2024-05-26 16:46
Hi, thanks for testing stuff.

I intend to write some functions to do the key initialization for you with the appropriate templates. Thanks for the guidance!

I don't think I'll add support for `go-tpm-tools`  shorthands in `go-tpm-keyfiles` as it still uses the legacy API with no transport security.

**Comment by salrashid123** [comment] 2024-05-26 16:58
sure, re: `go-tpm-tools` integration.  thats perfectly fine (my comment was just a general comment about the ecosystem;  i'll mention on go-tpm-tools github on how to use these keyfiles later for easier management (or they could have it on their readme, etc))

**Comment by Foxboron** [comment] 2024-05-30 18:23
Yo,

I was hacking a bit on the TPM parts and something doesn't make sense to me.

In your example code the `mykey.pem` key has the `parent` `0x40000001`, but the code you have written, at least on my system, makes a SRK with the handle `0x80ffffff` which seems.. off?

I assume this works because the SRK itself is correct but the handle won't be correct when written so I assume there is a "FlushHandle" step missing to get the correct persistent handle?

**Comment by salrashid123** [comment] 2024-05-30 20:01
ah..i think i didn't clarify what i did in the flow  [here](https://gist.github.com/salrashid123/6d355e4f03b124c085f780a9b3555dc8)

what i was basically doing is using `openssl` to create the key and then this library to read that in after i initialized the parent with the appropriate EK Template from the specifications

(` tpm2tss-genkey` defaults to that permanent parent unless you specified another one)

so basically, the first step is to 

```bash
$ uname -a
Linux d11 5.10.0-29-cloud-amd64 #1 SMP Debian 5.10.216-1 (2024-05-03) x86_64 GNU/Linux

$ openssl version
OpenSSL 1.1.1w  11 Sep 2023

$ tpm2tss-genkey -a rsa mykey.pem

# openssl asn1parse -inform PEM -in mykey.pem
    0:d=0  hl=4 l= 530 cons: SEQUENCE          
    4:d=1  hl=2 l=   6 prim: OBJECT            :2.23.133.10.1.3
   12:d=1  hl=2 l=   3 cons: cont [ 0 ]        
   14:d=2  hl=2 l=   1 prim: BOOLEAN           :255
   17:d=1  hl=2 l=   4 prim: INTEGER           :40000001
   23:d=1  hl=4 l= 280 prim: OCTET STRING      [HEX DUMP]:01160001000B000604720000001000100800000100010100DA5C0B389BF4F7C402ECAD1C79A1A51CF1C126994FB8D10D8FB440297F5D4788FCA6AD31FD63A41AE123E335AB85E93DBBE2098CAF22D233C70EE05C7467E0BE4B237EE3862AB3855110215715192DC7D54EC06A6DAB2C674B54BF078D40721E67B523CCEB8C43617C0E5544A788612A087642394B142774D9CC5A8713D13DAA9754A0F879FA785F2C518C652569692E765AE5F96ABF779E3DC806E66DFB0357CF99AAA9890A28D7707D75CD82F96F637ED3DAC804BAB172330CEB68F3A1EEE7B5628740D45FDB8FD34AA3D4BFCD58C65BAE5E31BADA75D5CD991C93EB8A2F4B31C2026012970CA009D2D0932B97040BEBE05C888F46385E72B1E20158283B1B
  307:d=1  hl=3 l= 224 prim: OCTET STRING      [HEX DUMP]:00DE00205851BC70A1FBAC1DF77D95822447C08B93DCCC4936CD3FB4742A5C8F620EAC9C00106C48B9DFAF573F8CC8289CA48D050F9085DF02C18113134BFA411574608799CB4DE3B3A317163C48118EA2BF35F2C86B47A9B00FD538ECE4EC1C2D2E34956450E8B2FD19FE7B4429C44532477F0AF8E055850E042BF6632E7C1732DADF32872E0066295705CDD877D486889DB464B16D12C1DB70497DFCBD5372C9344036F2924527AA87B37B971898C9FB4FBE11B3F9C8AFB98A48855B801040FD7B1028B36A0010B2E9451984CDCE50498DB9F1BE01EE0482206D57F1082EE5
```

even tried it on a raspberrypi with a real TPM though it shoud't make a difference

```bash
root@raspberrypi:~# uname -a
Linux raspberrypi 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux
root@raspberrypi:~#  openssl version
OpenSSL 1.1.1d  10 Sep 2019


root@raspberrypi:~# tpm2tss-genkey -a rsa mykey.pem
root@raspberrypi:~# openssl asn1parse -inform PEM -in mykey.pem
	    0:d=0  hl=4 l= 498 cons: SEQUENCE          
	    4:d=1  hl=2 l=   6 prim: OBJECT            :2.23.133.10.1.3
	   12:d=1  hl=2 l=   3 cons: cont [ 0 ]        
	   14:d=2  hl=2 l=   1 prim: BOOLEAN           :255
	   17:d=1  hl=2 l=   4 prim: INTEGER           :40000001
	   23:d=1  hl=4 l= 280 prim: OCTET STRING      [HEX DUMP]:01160001000B000604720000001000100800000100010100C3FB84EE6D16FCCEC86F7AB412C3D3176E56D08B3EBF98EF364DBBDF37F350D39B9A1C8C5780F05810B7F939B75758486313ECD955BC548E160507DF689E2D02FE92698D8C327059F2E2FC56438D5F37C67B479E828D089F4A8045091D39AC36FE72901673B736AB0C11FF554CA3CA34E7A8B627A15109A2705C8B250793D8F7FC983E93B40B34EE5680CC9E0F6611E2B1F1057C2DDE96B8184C9FEBF3C55B4951AEC92BD7E3D1491AF291562D0437499CAB65CC5FFDDCEC3251A1F87ED0094F0E647B0094D467BC72EF79FA461F2F3F476E46C13DF36ECAD21E74D384B3E98FA6252DF6AE136580F7C43D9302DD28F03B93E61EC5A6099E7E1B3BD3B92DA23B
	  307:d=1  hl=3 l= 192 prim: OCTET STRING      [HEX DUMP]:00BE0020B488FF763E5A4EAC3B07D78362A4F1E86830BBCBD375365C8EB6CC247D97B2260010B7D2BB6AB49C2D23050B8158E0F6F98938416535DB07292CEAEF8F6D56EB0F6B249767E9D7E261046EDD4DCBAC8D8C38117632E1A0DDB13DD7897D2676BB92FE50F32E462D7FFDB454A293B272181EA115270F6AA932C47394E14ADC4376A55F575563407B51AAC5AE0464775082C5DDCCDF72B326B2793BB22164189A8F0532111CBC44F2990FB4A4CD61D2600C04EE3FB5D64147D9F94702B1
		
```

**Comment by Foxboron** [comment] 2024-05-30 20:05
All of that makes sense. The issue is the `go-tpm` code as `primary.ObjectHandle,` is not going to point to the persistent handle `0x40000001`, which is defined in the key, but some  handle with MSO `0x80`.

**Comment by salrashid123** [comment] 2024-05-30 20:11
ok i'm going to step though what i just have in the gist and print handles, etc  and see how i arrived at the false positive for that gist...(sorry for the confusion)

**Comment by Foxboron** [comment] 2024-05-30 20:14
No worries, my code is also wrong and I'm mostly just confused at what I'm missing :)

**Comment by salrashid123** [comment] 2024-05-30 22:07
i'll take a closer look at what  openssl is doing [here](https://github.com/tpm2-software/tpm2-tss-engine/blob/master/src/tpm2-tss-engine-common.c) but my read on the specs suggests you have to gen a primary with that known/standard ecc template (which'll give the same decryption key).


```golang

// read the keyfile in 
	c, err := os.ReadFile(*in)
	key, err := keyfile.Decode(c)

// specify its parent directly
	primary, err := tpm2.CreatePrimary{
		PrimaryHandle: key.Parent,
		InPublic:      tpm2.New2B(ECCSRKHTemplate),
	}.Execute(rwr)

// now the actual key can get loaded from that parent
	regenRSAKey, err := tpm2.Load{
		ParentHandle: tpm2.AuthHandle{
			Handle: primary.ObjectHandle,
			Name:   tpm2.TPM2BName(primary.Name),
			Auth:   tpm2.PasswordAuth([]byte("")),
		},
		InPublic:  key.Pubkey,
		InPrivate: key.Privkey,
	}.Execute(rwr)
```

---

(or there maybe just some other way to load the key i'm unaware of)

**Comment by Foxboron** [comment] 2024-05-31 08:48
Ohh, I realized my confusion now. "on the handle" in the spec means "set 0x40 as PrimaryHandle" but we don't use the resulting SRK Handle inside the keyfile, we use the `tpm2.TPMRHOwner` handle.

While I thought we always use the handle of the CreatePrimary call inside the keyfile :)

Thanks!

**Comment by salrashid123** [comment] 2024-05-31 22:21
yeah, the specs could be a bit clearer (esp that section).  

anyway, i used `tpm2_tools` to create a primary by hand that is compatible with those specs...it took some research for it to work..

```bash
# create primary
printf '\x00\x00' > unique.dat
tpm2_createprimary -C o -G ecc  -g sha256  -c primary.ctx -a "fixedtpm|fixedparent|sensitivedataorigin|userwithauth|noda|restricted|decrypt" -u unique.dat

# create key
tpm2_create -G rsa2048:rsassa:null -g sha256 -u key.pub -r key.priv -C primary.ctx
tpm2_load -C primary.ctx -u key.pub -r key.priv -c key.ctx 

## generate the PEM representation
tpm2tss-genkey -u key.pub -r key.priv private.pem
```

see 
[tpm2 primarykey for (eg TCG EK Credential Profile H-2 profile](https://gist.github.com/salrashid123/9822b151ebb66f4083c5f71fd4cdbe40)

**Comment by Foxboron** [comment] 2024-05-31 22:23
Yep, thanks for the support :)!

**Comment by Foxboron** [comment] 2024-06-02 11:29
I've pushed the TPM pieces to this library now. Hopefully less breaking API changes in the future going forward :) Feel free to come with feedback if you have any.

**Comment by salrashid123** [comment] 2024-06-02 19:59
hi- i'll try it out more this later this week but quick test with permanent keys doesn't work because the primary template isn't setup correctly.

my previous comment was about the tpm2_tools equivalent of the H2 template thats described in the specs.  You'll need to create a primary with that specific template and values for keys with permanent parent

if you create a key with default values 

```bash
tpm2tss-genkey private.pem
```

the H2 template is used which is what the createprimary below does too


```bash
printf '\x00\x00' > unique.dat
tpm2_createprimary -C o -G ecc \
   -g sha256  -c primary.ctx \
   -a "fixedtpm|fixedparent|sensitivedataorigin|userwithauth|noda|restricted|decrypt" -u unique.dat

tpm2_create -G rsa2048:rsassa:null -g sha256 -u key.pub -r key.priv -C primary.ctx
tpm2_load -C primary.ctx -u key.pub -r key.priv -c key.ctx 

## save the key as PEM
tpm2tss-genkey -u key.pub -r key.priv private.pem
```

the child key can't get loaded with this library since the specific template isn't specified  (eg `ECCSRK_H2_Template` from above....

i made a tiny modification to `GetParentHandle` here to accomodate that

```golang
func GetParentHandle(sess *keyfile.TPMSession, parent tpm2.TPMHandle, ownerauth []byte) (*tpm2.AuthHandle, error) {
	var parenthandle tpm2.AuthHandle

	if keyfile.IsMSO(parent, keyfile.TPM_HT_PERMANENT) {

		//Generate a primary using the specified format described in
		// ASN.1 Specification for TPM 2.0 Key Files where the template h-2 is described in pg 43 TCG EK Credential Profile
		// https://trustedcomputinggroup.org/wp-content/uploads/TCG_IWG_EKCredentialProfile_v2p4_r2_10feb2021.pdf
		// use the H2 template if the parent is permanent...
		srkHandle, pub, err := CreateSRK(sess, parent, ownerauth, ECCSRK_H2_Template)
		if err != nil {
			return nil, err
		}
		sess.SetSalted(srkHandle.Handle, *pub)
		parenthandle = *srkHandle
```

my 2c:  i'm really just looking at this library to save/load keys in a standard format and way.. stuff like new keys, signing, etc is kinda really hard to get right and clean via wrapper/library so i'd compose those directly.

**Comment by Foxboron** [comment] 2024-06-02 20:03
> my 2c: i'm really just looking at this library to save/load keys in a standard format and way.. stuff like new keys, signing, etc is kinda really hard to get right and clean via wrapper/library so i'd compose those directly.

Yes, I get that. I've moved this to be easily created with `NewKey()`.

Thanks for the feedback!

**Comment by Foxboron** [comment] 2024-06-05 20:26
I've implemented some end-to-end testing with `swtpm` and the `openssl` provider.

It should hopefully catch regressions from this library :)

https://github.com/Foxboron/go-tpm-keyfiles/blob/master/keyfile_test.go#L159

Thanks for your help. I'll close this issue and feel free to continue giving feedback in issues in the future as well!

**Closed by Foxboron** 2024-06-05 20:26 UTC
